apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: "dev"
secretGenerator:
- name: mysql-pass
  literals:
  - password=pwadmin
resources:
  - mysql-deploy.yaml
  - wp-deploy.yaml
  - gw-vs.yaml
